### ISSUE TITLE
sshkey list, is failing.

### ISSUE THREAD

**Issue by chiplipop** [rmoriz/knife-digital_ocean#69]
Running on osx yosemite with rbenv, tried with ruby 2.2.1 and 2.1.9.
```
$ knife digital_ocean sshkey list -VV
INFO: Using configuration from /Users/yarivmathov/code/yeah/.chef/knife.rb
/Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/kartograph-0.2.2/lib/kartograph/map.rb:14:in `property': undefined method `+' for :read:Symbol (NoMethodError)
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:9:in `block in <class:SSHKeyMapping>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/kartograph-0.2.2/lib/kartograph/dsl.rb:12:in `instance_eval'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/kartograph-0.2.2/lib/kartograph/dsl.rb:12:in `kartograph'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:5:in `<class:SSHKeyMapping>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:2:in `<module:DropletKit>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:1:in `<top (required)>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/resources/ssh_key_resource.rb:7:in `block (3 levels) in <class:SSHKeyResource>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.3/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.3/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:68:in `retrieve'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:60:in `fetch_next_page'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:26:in `each'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/knife-digital_ocean-2.3.2/lib/chef/knife/digital_ocean_sshkey_list.rb:35:in `sort_by'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/knife-digital_ocean-2.3.2/lib/chef/knife/digital_ocean_sshkey_list.rb:35:in `run'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/knife.rb:214:in `run'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/lib/chef/application/knife.rb:138:in `run'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/chef-12.1.1/bin/knife:25:in `<top (required)>'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/bin/knife:23:in `load'
	from /Users/yarivmathov/.rbenv/versions/2.2.1/bin/knife:23:in `<main>'
```

**Comment by bb2bb** [comment]
I'm seeing the same issue.  run on Ubuntu 14.04 32bit
```ruby
knife digital_ocean sshkey list -VV                                                                                                                 17:04
/home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/kartograph-0.2.2/lib/kartograph/map.rb:14:in `property': undefined method `+' for :read:Symbol (NoMethodError)
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:9:in `block in <class:SSHKeyMapping>'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/kartograph-0.2.2/lib/kartograph/dsl.rb:12:in `instance_eval'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/kartograph-0.2.2/lib/kartograph/dsl.rb:12:in `kartograph'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:5:in `<class:SSHKeyMapping>'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:2:in `<module:DropletKit>'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:1:in `<top (required)>'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/resources/ssh_key_resource.rb:7:in `block (3 levels) in <class:SSHKeyResource>'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.3/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.3/lib/resource_kit/action_invoker.rb:19:in `handle_response'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:68:in `retrieve'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:60:in `fetch_next_page'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/droplet_kit-1.1.3/lib/droplet_kit/paginated_resource.rb:26:in `each'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/knife-digital_ocean-2.3.2/lib/chef/knife/digital_ocean_sshkey_list.rb:35:in `sort_by'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/knife-digital_ocean-2.3.2/lib/chef/knife/digital_ocean_sshkey_list.rb:35:in `run'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-11.18.6/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-11.18.6/lib/chef/knife.rb:174:in `run'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-11.18.6/lib/chef/application/knife.rb:139:in `run'
	from /home/user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-11.18.6/bin/knife:25:in `<top (required)>'
	from /home/user/.rbenv/versions/2.1.5/bin/knife:23:in `load'
	from /home/user/.rbenv/versions/2.1.5/bin/knife:23:in `<main>'
```

**Comment by chiplipop** [comment]
If this helps anyone: I managed to overcome this by simply commenting out /gems/kartograph-0.2.2/lib/kartograph/map.rb:14.
Sorry but i have no time right now to investigate.

**Comment by phillbaker** [comment]
`droplet_kit` should be bumped to `~> 1.2.0` (https://github.com/rmoriz/knife-digital_ocean/blob/master/knife-digital_ocean.gemspec#L17), or lock one of droplet_kit's dependencies (lock kartograph to 0.2.0) in the Gemfile as per: https://github.com/digitalocean/droplet_kit/issues/37#issuecomment-77770605.

**Comment by gregf** [comment]
Fixed in master, I'll cut a release within the hour.
